-- Owner-focused vehicle ingestion schema.
-- No auth/profile/role tables are created in this phase.

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  make text not null check (length(btrim(make)) > 0),
  model text not null check (length(btrim(model)) > 0),
  year smallint not null check (year between 1886 and 2100),
  vin text,
  created_at timestamptz not null default now()
);

create unique index if not exists vehicles_vin_unique
  on public.vehicles (upper(vin))
  where vin is not null;

create table if not exists public.telemetry_readings (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  recorded_at timestamptz not null,
  rpm double precision not null check (rpm >= 0),
  speed_kph double precision not null check (speed_kph >= 0),
  coolant_temp_c double precision not null,
  intake_temp_c double precision not null,
  engine_load_pct double precision not null check (engine_load_pct between 0 and 100),
  throttle_position_pct double precision not null check (throttle_position_pct between 0 and 100),
  maf_g_per_s double precision not null check (maf_g_per_s >= 0),
  created_at timestamptz not null default now()
);

create index if not exists telemetry_readings_vehicle_recorded_idx
  on public.telemetry_readings (vehicle_id, recorded_at desc);

create table if not exists public.vehicle_health_snapshots (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  score smallint not null check (score between 0 and 100),
  status text not null check (status in ('good', 'attention', 'warning', 'critical')),
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists vehicle_health_snapshots_vehicle_recorded_idx
  on public.vehicle_health_snapshots (vehicle_id, recorded_at desc);

create table if not exists public.vehicle_system_health (
  id uuid primary key default gen_random_uuid(),
  snapshot_id uuid not null references public.vehicle_health_snapshots (id) on delete cascade,
  name text not null,
  status text not null check (status in ('normal', 'attention', 'warning', 'critical')),
  description text,
  icon text not null,
  created_at timestamptz not null default now(),
  unique (snapshot_id, name)
);

create table if not exists public.anomalies (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  source_key text,
  title text not null,
  severity text not null check (severity in ('low', 'moderate', 'high', 'critical')),
  status text not null,
  description text not null,
  detailed_description text not null,
  detected_at timestamptz not null,
  contributing_factors text[] not null default '{}',
  recommended_checks text[] not null default '{}',
  supporting_telemetry jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists anomalies_vehicle_detected_idx
  on public.anomalies (vehicle_id, detected_at desc);

create table if not exists public.diagnostic_codes (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  code text not null,
  description text not null,
  status text not null,
  detected_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists diagnostic_codes_vehicle_detected_idx
  on public.diagnostic_codes (vehicle_id, detected_at desc);

create table if not exists public.health_events (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  anomaly_id uuid references public.anomalies (id) on delete set null,
  occurred_at timestamptz not null,
  score smallint not null check (score between 0 and 100),
  description text not null,
  created_at timestamptz not null default now()
);

create index if not exists health_events_vehicle_occurred_idx
  on public.health_events (vehicle_id, occurred_at desc);

create table if not exists public.drive_reports (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  date date not null,
  distance_km double precision not null check (distance_km >= 0),
  average_speed_kph double precision not null check (average_speed_kph >= 0),
  anomaly_count integer not null default 0 check (anomaly_count >= 0),
  diagnostic_code_count integer not null default 0 check (diagnostic_code_count >= 0),
  health_score smallint not null check (health_score between 0 and 100),
  summary text not null,
  system_statuses jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists drive_reports_vehicle_date_idx
  on public.drive_reports (vehicle_id, date desc);

create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_conversations_vehicle_updated_idx
  on public.ai_conversations (vehicle_id, updated_at desc);

create table if not exists public.ai_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.ai_conversations (id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  evidence text[] not null default '{}',
  rag_supported boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists ai_messages_conversation_created_idx
  on public.ai_messages (conversation_id, created_at);

-- Secure by default: RLS is enabled with no anonymous policies. Add owner-scoped
-- policies when authentication is introduced; do not expose vehicle data publicly.
alter table public.vehicles enable row level security;
alter table public.telemetry_readings enable row level security;
alter table public.vehicle_health_snapshots enable row level security;
alter table public.vehicle_system_health enable row level security;
alter table public.anomalies enable row level security;
alter table public.diagnostic_codes enable row level security;
alter table public.health_events enable row level security;
alter table public.drive_reports enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;
